### ISSUE TITLE
How to calculate the probability that two AIs are equally good?

### ISSUE THREAD

**Issue by Belissimo-T** [seekers-dev/seekers-py#27]
We have to keep in mind that a single AI might perform differently against different opponents. Simply only keeping the best and passing them to the next round like used in football has little meaning. 

Also, how do we calculate the probability that two AIs are equally good given their scores and the passed playtime? This can be useful so we only need to play until we are 95% sure or sth.

**Comment by Belissimo-T** [comment]
@karl-zschiebsch @joendter What do you think?

**Comment by Belissimo-T** [comment]
We could let all AIs compete against each other (n² possiblities). Then we just rank by the won games. If there is a draw we could do the same with only these AIs again.

**Comment by Belissimo-T** [comment]
To calculate the probabiblity that two AIs are equal, I had the idea to idealize each player as a weighted coin that is flipped every frame. That means we assume that each frame both AIs each have a constant chance of scoring a point. 

Then we could calculate the chance that an AI really has that specific chance of gaining a point.
$P_\text{measured} = \frac{\text{points of player n}}{\text{passed time}}$
$P(P_\text{actual}) = P_\text{measured}) = \binom{\text{passed time}}{\text{points of player n}} \cdot {P_\text{measured}}^\text{points of player n} \cdot (1 - P_\text{measured})^{\text{passed time} - \text{points of player n}}$

**Comment by karl-zschiebsch** [comment]
> We could let all AIs compete against each other (~n² or ~n²/2 possiblities). Then we just rank by the number of won games. If there is a draw we could do the same with only these AIs again.

That sounds good, and it would be the easiest to add.

**Comment by Belissimo-T** [comment]
> That sounds good, and it would be the easiest to add.

Great! Now we just need to decide how long to run each match. Ideally, we would calculate the chance that both AIs are not equally good and wait until that reaches 95%.

**Comment by Kiyotoko** [comment]
Can we close this issue? This issue is now over a year old and the problem was solved.

**Comment by Belissimo-T** [comment]
@Kiyotoko Problem not really solved but let's close for now.
